force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Eats__c.field-meta.xml
<CustomField>
    <fullName>Eats__c</fullName>
    <label>Eats</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Says__c.field-meta.xml
<CustomField>
    <fullName>Says__c</fullName>
    <label>Says</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnimalTriggerHandler.cls
public class AnimalTriggerHandler {
    
    @future(callout=true)
    public static void getAnimalData(List<String> ids){
        List<String> externalIds = new List<String>();
        List<Animal__c> animalList = new List<Animal__c>();
        System.debug('ids: '+ ids);
        
        for(String id : ids){            
        	AnimalServiceWrapper animalWrap = AnimalServiceWrapper.parse(AnimalsCallouts.makeGetDataCallout(id));            
            System.debug(animalWrap.animal.name);
            
            Animal__c anim = new Animal__c (External_Id__c = animalWrap.animal.id,
                                           Name = animalWrap.animal.name,
                                           Eats__c = animalWrap.animal.eats,
                                           Says__c = animalWrap.animal.says);
            animalList.add(anim);
        }
       	System.debug('animalList: '+ animalList);
        
        upsert animalList External_Id__c;
    }
        
}