force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Eats__c.field-meta.xml
<CustomField>
    <fullName>Eats__c</fullName>
    <label>Eats</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Says__c.field-meta.xml
<CustomField>
    <fullName>Says__c</fullName>
    <label>Says</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAnimalCMPController.cls
public class GetAnimalCMPController {
    
    @AuraEnabled
    public static List<Animal__c> getAnimalData(String inputId){
        
        List<Animal__c> animal = new List<Animal__c>();
        
         if (inputId == null || String.isBlank(inputId))
            animal = [SELECT External_Id__c, Name, Eats__c, Says__c FROM Animal__c LIMIT 15];
         else if (inputId instanceOf ID)
            animal = [SELECT External_Id__c, Name, Eats__c, Says__c FROM Animal__c WHERE Id = :inputId];
         else 
            animal = [SELECT External_Id__c, Name, Eats__c, Says__c FROM Animal__c WHERE External_Id__c = :inputId];
    		
        return animal;
	}
}