force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Eats__c.field-meta.xml
<CustomField>
    <fullName>Eats__c</fullName>
    <label>Eats</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Says__c.field-meta.xml
<CustomField>
    <fullName>Says__c</fullName>
    <label>Says</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SearchAnimalLwcController.cls
public with sharing class SearchAnimalLwcController {
	@AuraEnabled(cacheable=true)
    public static List<Animal__c> getContactList(string searchKey) {
        //string searchKeyword = '%' + searchKey + '%';
		
       // create contact list to store search result 
        List<Animal__c> animalList = new List<Animal__c>();
     
	   // query contact records
        for (Animal__c animal_i : [Select id,Name,Says__c,Eats__C,External_Id__c
                            From Animal__c
                            WHERE External_Id__c = :searchKey]){
           animalList.add(animal_i);
        }
        
         if(animalList.size() == 0){
            throw new AuraHandledException('No Record Found..'); 
         }
         
        return animalList;
    }
}