force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/School_Assigned_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>School_Assigned_Timestamp__c</fullName>
    <label>School Assigned Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/StudentTriggerHandlerTest.cls
@isTest
public class StudentTriggerHandlerTest {
	
    @isTest
    static void insertStudentTest(){
        
        Test.startTest();
        List<String> studentIds = new List<String>();
            studentIds = TestDataFactory.createStudentWithSchool(2,2);
        System.debug('studentsData ' + studentIds);
        Test.stopTest();
 
        List<Student__c> studentsData = [SELECT School_Assigned_Timestamp__c FROM Student__c WHERE Id IN :studentIds];
        
        for(Student__c s : studentsData){
            DateTime expected = s.School_Assigned_Timestamp__c;
            System.debug('expected ' + expected);
            System.assertEquals(System.now(), expected);
        }
        
        
    }
    
    @isTest
    static void updateStudentsSchool(){
        
        Test.startTest();
        ID studentId = TestDataFactory.updateParentSchool();
        Test.stopTest();
        
        Student__c actual = [SELECT School_Assigned_Timestamp__c FROM Student__c WHERE Id=:studentId];
        
        System.assertEquals(System.now(), actual.School_Assigned_Timestamp__c);
        
    }
    
    @isTest
    static void eraseStudentsSchool(){
        
        Test.startTest();
        ID studentId = TestDataFactory.eraseParentSchool();
        Test.stopTest();
        
        Student__c actual = [SELECT School_Assigned_Timestamp__c FROM Student__c WHERE Id=:studentId];
        
        System.assertEquals(null, actual.School_Assigned_Timestamp__c);
    }
}